/**
 * Data Layer — Supabase implementation
 *
 * This is the canonical data access module after Firebase → Supabase migration.
 * All Firestore direct calls in hooks/pages should be replaced with these helpers.
 *
 * API surface is intentionally similar to the old firebaseDataLayer so call-sites
 * need minimal changes.
 */

import { supabase, supabaseAdmin } from './supabase';

export type DataLayer = 'supabase';
export const DATA_LAYER: DataLayer = 'supabase';

// Operator map from Firestore syntax to Supabase PostgREST filter methods
const OP_MAP: Record<string, string> = {
  '==': 'eq',
  '!=': 'neq',
  '>': 'gt',
  '>=': 'gte',
  '<': 'lt',
  '<=': 'lte',
  'in': 'in',
  'not-in': 'not.in',
  'array-contains': 'cs',     // JSONB contains
  'array-contains-any': 'ov', // JSONB overlaps
};

function client() {
  // Prefer admin (server) key when available, fall back to anon (browser)
  return supabaseAdmin ?? supabase;
}

function requireClient() {
  const c = client();
  if (!c) throw new Error('[DataLayer] Supabase not configured.');
  return c;
}

/** AI/extractor legacy keys — not columns on public.companies */
function sanitizeCompanyPayload<T extends Record<string, unknown>>(data: T): T {
  const next = { ...data };
  delete next.city;
  delete next.address;
  return next;
}

// ============================================================
// Core CRUD
// ============================================================

/** Fetch a single row by id */
async function getDoc<T>(table: string, id: string): Promise<T | null> {
  const { data, error } = await requireClient()
    .from(table)
    .select('*')
    .eq('id', id)
    .maybeSingle();
  if (error) throw error;
  return data as T | null;
}

/** Query rows with optional filters, ordering, and limit */
async function queryDocs<T>(
  table: string,
  filters: Array<{ field: string; op: string; value: unknown }> = [],
  options?: { orderBy?: { field: string; direction?: 'asc' | 'desc' }; limit?: number }
): Promise<T[]> {
  let q = requireClient().from(table).select('*');

  for (const f of filters) {
    const method = OP_MAP[f.op] ?? 'eq';
    q = (q as any)[method](f.field, f.value);
  }

  if (options?.orderBy) {
    q = q.order(options.orderBy.field, { ascending: options.orderBy.direction !== 'desc' });
  }
  if (options?.limit) {
    q = q.limit(options.limit);
  }

  const { data, error } = await q;
  if (error) throw error;
  return (data ?? []) as T[];
}

/** Upsert (insert or update) a row */
async function setDoc(table: string, id: string, data: Record<string, unknown>): Promise<void> {
  const row = table === 'companies' ? sanitizeCompanyPayload({ ...data, id }) : { ...data, id };
  const { error } = await requireClient()
    .from(table)
    .upsert(row, { onConflict: 'id' });
  if (error) throw error;
}

/** Update specific fields on a row */
async function updateDoc(table: string, id: string, data: Record<string, unknown>): Promise<void> {
  const payload = table === 'companies' ? sanitizeCompanyPayload({ ...data }) : data;
  const { error } = await requireClient()
    .from(table)
    .update(payload)
    .eq('id', id);
  if (error) throw error;
}

/** Delete a row */
async function deleteDoc(table: string, id: string): Promise<void> {
  const { error } = await requireClient().from(table).delete().eq('id', id);
  if (error) throw error;
}

/** Insert a new row (no id required — auto-generated by DB if not supplied) */
async function addDoc(table: string, data: Record<string, unknown>): Promise<{ id: string }> {
  const { data: inserted, error } = await requireClient()
    .from(table)
    .insert(data)
    .select('id')
    .single();
  if (error) throw error;
  return inserted as { id: string };
}

// ============================================================
// Batch helpers (Supabase doesn't have a Firestore-style batch,
// but we can run multiple upserts/updates in a single RPC or
// use Promise.all for independent writes)
// ============================================================

/** Batch update multiple rows in the same table */
async function batchUpdate(
  table: string,
  updates: Array<{ id: string; data: Record<string, unknown> }>
): Promise<void> {
  await Promise.all(updates.map(({ id, data }) => updateDoc(table, id, data)));
}

/** Batch delete multiple rows in the same table */
async function batchDelete(table: string, ids: string[]): Promise<void> {
  const { error } = await requireClient().from(table).delete().in('id', ids);
  if (error) throw error;
}

// ============================================================
// Real-time subscriptions (replaces Firestore onSnapshot)
// ============================================================

/**
 * Subscribe to real-time changes on a table.
 * Returns an unsubscribe function.
 */
function onSnapshot<T>(
  table: string,
  filters: Array<{ field: string; op: string; value: unknown }>,
  callback: (docs: T[]) => void,
  onError?: (error: Error) => void
): () => void {
  const c = requireClient();

  // Initial fetch
  queryDocs<T>(table, filters)
    .then(callback)
    .catch(err => onError?.(err as Error));

  const channel = c
    .channel(`realtime:${table}:${Date.now()}`)
    .on(
      'postgres_changes',
      { event: '*', schema: 'public', table },
      () => {
        queryDocs<T>(table, filters)
          .then(callback)
          .catch(err => onError?.(err as Error));
      }
    )
    .subscribe();

  return () => {
    c.removeChannel(channel);
  };
}

// ============================================================
// ID counter (replaces Firestore runTransaction on metadata doc)
// ============================================================

/** Get next auto-incremented company ID via Postgres function */
async function getNextCompanyId(): Promise<number> {
  const { data, error } = await requireClient().rpc('get_next_company_id');
  if (error) throw error;
  return data as number;
}

/** Reserve `count` sequential company IDs; returns the first one */
async function getNextCompanyIds(count: number): Promise<number[]> {
  const { data, error } = await requireClient().rpc('get_next_company_ids', { count });
  if (error) throw error;
  const startId = data as number;
  return Array.from({ length: count }, (_, i) => startId + i);
}

// ============================================================
// Exported data layer object (matches old firebaseDataLayer API)
// ============================================================

export const dataLayer = {
  getDoc,
  query: queryDocs,
  setDoc,
  updateDoc,
  deleteDoc,
  addDoc,
  batchUpdate,
  batchDelete,
  onSnapshot,
  getNextCompanyId,
  getNextCompanyIds,
  serverTimestamp: () => new Date().toISOString(),
};

// Named exports for direct import by call-sites
export {
  getDoc,
  queryDocs,
  setDoc,
  updateDoc,
  deleteDoc,
  addDoc,
  batchUpdate,
  batchDelete,
  onSnapshot,
  getNextCompanyId,
  getNextCompanyIds,
};

console.log('[DataLayer] Using: supabase');
